### ISSUE TITLE
Better explanation on how to run tests locally for development

### ISSUE THREAD

**Issue by nokrosis** [nicp0nim/rest-api#5]
**Is your feature request related to a problem? Please describe.**
I'm trying to run recently added tests locally so I can write and run my own tests. I can't. I keep getting:

`SQLSTATE[HY000] [2002] Connection refused (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')`

or

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'redirect' cannot be null`

**Describe the solution you'd like**
I'd like to have clear step by step documentation on how to setup testing to run locally in the development workflow.

**Describe alternatives you've considered**
Add commands to run in order to get tests locally running. Specify what should be changed in configuration.

**Comment by nicp0nim** [comment]
As default tests are configured to work with travis when you push commit to github repo, but if you want to run tests local go to phpunit.xml file in root directory and change `DB_CONNECTION` value to sqlite. Then as normally run command `./vendor/bin/phpunit`.
Remember to change that value back for `testing` when you push repo to github, otherwize your commit test will fail.
